/* cwmp-1-1.h
   Generated by wsdl2h 1.2.11 from cwmp-1-1.wsdl and typemap.dat
   2008-09-30 10:26:18 GMT
   Copyright (C) 2001-2008 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * urn:dslforum-org:cwmp-1-1                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

cwmp1 = "urn:dslforum-org:cwmp-1-1"

*/

//gsoap cwmp1 schema namespace:	urn:dslforum-org:cwmp-1-1
//gsoap cwmp1 schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "SOAP-ENC:base64".
struct SOAP_ENC__base64 { unsigned char *__ptr; int __size; };

/// Primitive built-in type "xs:anySimpleType"
typedef char* xsd__anySimpleType;

/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };


/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
typedef char* cwmp1__FaultCodeType;

/// "urn:dslforum-org:cwmp-1-1":ParameterKeyType is a simpleType restriction of xs:string.
/// Length of this string is within 0..32 characters
typedef char* cwmp1__ParameterKeyType:32;

/// "urn:dslforum-org:cwmp-1-1":CommandKeyType is a simpleType restriction of xs:string.
/// Length of this string is within 0..32 characters
typedef char* cwmp1__CommandKeyType:32;

/// "urn:dslforum-org:cwmp-1-1":ObjectNameType is a simpleType restriction of xs:string.
/// Length of this string is within 0..256 characters
/// Content pattern is ".*\\."
typedef char* cwmp1__ObjectNameType ".*\\.":256;

/// "urn:dslforum-org:cwmp-1-1":FaultStruct is a complexType.
/// @brief Fault information for TransferComplete and AutonomousTransferComplete
struct cwmp1__FaultStruct
{
/// @brief Transfer fault codes

/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
/// union of values from "xs:unsignedInt"
    char*                                                              
                                         FaultCode                      1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         FaultString                    1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":DeviceIdStruct is a complexType.
struct cwmp1__DeviceIdStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Manufacturer                   1;	///< Required element.
/// Length of this string is exactly 6 characters
/// Content pattern is "[0-9A-F]{6}"
    char*                                                              
                                         OUI                            1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         ProductClass                   1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         SerialNumber                   1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":EventStruct is a complexType.
struct cwmp1__EventStruct
{
/// Length of this string is within 0..64 characters
/// Content pattern is "0 BOOTSTRAP"
/// Content pattern is "1 BOOT"
/// Content pattern is "2 PERIODIC"
/// Content pattern is "3 SCHEDULED"
/// Content pattern is "4 VALUE CHANGE"
/// Content pattern is "5 KICKED"
/// Content pattern is "6 CONNECTION REQUEST"
/// Content pattern is "7 TRANSFER COMPLETE"
/// Content pattern is "8 DIAGNOSTICS COMPLETE"
/// Content pattern is "9 REQUEST DOWNLOAD"
/// Content pattern is "10 AUTONOMOUS TRANSFER COMPLETE"
/// Content pattern is "\\d+( \\S+)+"
/// Content pattern is "M Reboot"
/// Content pattern is "M ScheduleInform"
/// Content pattern is "M Download"
/// Content pattern is "M Upload"
/// Content pattern is "M \\S+"
/// Content pattern is "M X_\\S+"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         EventCode                      1;	///< Required element.
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterValueStruct is a complexType.
struct cwmp1__ParameterValueStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Element Value of type xs:anySimpleType.
    xsd__anySimpleType                   Value                          1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterInfoStruct is a complexType.
struct cwmp1__ParameterInfoStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Element Writable of type xs:boolean.
    enum xsd__boolean                    Writable                       1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesStruct is a complexType.
struct cwmp1__SetParameterAttributesStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                        *Name                          ;	///< Nullable pointer.
/// Element NotificationChange of type xs:boolean.
    enum xsd__boolean                    NotificationChange             1;	///< Required element.
    enum _cwmp1__SetParameterAttributesStruct_Notification
    {
/// @brief Notification off. The CPE need not inform the ACS of a change to the specified parameter(s)
	_cwmp1__SetParameterAttributesStruct_Notification__0 = 0,	///< xs:int value="0"
/// @brief Passive notification. Whenever the specified parameter value changes, the CPE MUST include the new value in the ParameterList in the Inform message that is sent the next time a session is established to the ACS
	_cwmp1__SetParameterAttributesStruct_Notification__1 = 1,	///< xs:int value="1"
/// @brief Active notification. Whenever the specified parameter value changes, the CPE MUST initiate a session to the ACS, and include the new value in the ParameterList in the associated Inform message
	_cwmp1__SetParameterAttributesStruct_Notification__2 = 2,	///< xs:int value="2"
    }
                                         Notification                   1;	///< Required element.
/// Element AccessListChange of type xs:boolean.
    enum xsd__boolean                    AccessListChange               1;	///< Required element.
/// Element AccessList of type "urn:dslforum-org:cwmp-1-1":AccessList.
    struct cwmp1AccessList*              AccessList                     1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ParameterAttributeStruct is a complexType.
struct cwmp1__ParameterAttributeStruct
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Name                           1;	///< Required element.
    enum _cwmp1__ParameterAttributeStruct_Notification
    {
	_cwmp1__ParameterAttributeStruct_Notification__0 = 0,	///< xs:int value="0"
	_cwmp1__ParameterAttributeStruct_Notification__1 = 1,	///< xs:int value="1"
	_cwmp1__ParameterAttributeStruct_Notification__2 = 2,	///< xs:int value="2"
    }
                                         Notification                   1;	///< Required element.
/// Element AccessList of type "urn:dslforum-org:cwmp-1-1":AccessList.
    struct cwmp1AccessList*              AccessList                     1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":QueuedTransferStruct is a complexType.
struct cwmp1__QueuedTransferStruct
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
    enum _cwmp1__QueuedTransferStruct_State
    {
/// @brief 1 - Not yet started
	_cwmp1__QueuedTransferStruct_State__1 = 1,	///< xs:int value="1"
/// @brief 2 - In progress
	_cwmp1__QueuedTransferStruct_State__2 = 2,	///< xs:int value="2"
/// @brief 3 - Completed
	_cwmp1__QueuedTransferStruct_State__3 = 3,	///< xs:int value="3"
    }
                                         State                          1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":AllQueuedTransferStruct is a complexType.
struct cwmp1__AllQueuedTransferStruct
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
    enum _cwmp1__AllQueuedTransferStruct_State
    {
/// @brief 1 - Not yet started
	_cwmp1__AllQueuedTransferStruct_State__1 = 1,	///< xs:int value="1"
/// @brief 2 - In progress
	_cwmp1__AllQueuedTransferStruct_State__2 = 2,	///< xs:int value="2"
/// @brief 3 - Completed
	_cwmp1__AllQueuedTransferStruct_State__3 = 3,	///< xs:int value="3"
    }
                                         State                          1;	///< Required element.
/// Element IsDownload of type xs:boolean.
    enum xsd__boolean                    IsDownload                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "4 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":ArgStruct is a complexType.
struct cwmp1__ArgStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Name                           1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Value                          1;	///< Required element.
};

/// "urn:dslforum-org:cwmp-1-1":OptionStruct is a complexType.
struct cwmp1__OptionStruct
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         OptionName                     1;	///< Required element.
/// Element VoucherSN of type xs:unsignedInt.
    unsigned int                         VoucherSN                      1;	///< Required element.
    enum _cwmp1__OptionStruct_State
    {
/// @brief Option is disabled and not setup
	_cwmp1__OptionStruct_State__0 = 0,	///< xs:unsignedInt value="0"
/// @brief Option is enabled and not setup
	_cwmp1__OptionStruct_State__1 = 1,	///< xs:unsignedInt value="1"
/// @brief Option is disabled and setup
	_cwmp1__OptionStruct_State__2 = 2,	///< xs:unsignedInt value="2"
/// @brief Option is enabled and setup
	_cwmp1__OptionStruct_State__3 = 3,	///< xs:unsignedInt value="3"
    }
                                         State                          1;	///< Required element.
    enum _cwmp1__OptionStruct_Mode
    {
/// @brief 0 - Disabled
	_cwmp1__OptionStruct_Mode__0 = 0,	///< xs:int value="0"
/// @brief 1 - Enabled with expiration
	_cwmp1__OptionStruct_Mode__1 = 1,	///< xs:int value="1"
/// @brief 2 - Enabled without expiration
	_cwmp1__OptionStruct_Mode__2 = 2,	///< xs:int value="2"
    }
                                         Mode                           1;	///< Required element.
/// Element StartDate of type xs:dateTime.
    time_t                               StartDate                      1;	///< Required element.
/// Element ExpirationDate of type xs:dateTime.
    time_t*                              ExpirationDate                 0;	///< Optional element.
    enum _cwmp1__OptionStruct_IsTransferable
    {
/// @brief Non-transferable
	_cwmp1__OptionStruct_IsTransferable__0 = 0,	///< xs:int value="0"
/// @brief Transferable
	_cwmp1__OptionStruct_IsTransferable__1 = 1,	///< xs:int value="1"
    }
                                         IsTransferable                 1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Fault of complexType.

/// "urn:dslforum-org:cwmp-1-1":Fault is a complexType.
struct _cwmp1__Fault
{
/// Element FaultCode of type "urn:dslforum-org:cwmp-1-1":FaultCodeType.
    cwmp1__FaultCodeType                 FaultCode                      1;	///< Required element.
/// Element FaultString of type xs:string.
    char*                                FaultString                    0;	///< Optional element.
/// Size of SetParameterValuesFault array is 0..unbounded
    int                                  __sizeSetParameterValuesFault ;
    struct _cwmp1__Fault_SetParameterValuesFault
    {
/// Element ParameterName of type xs:string.
    char*                                ParameterName                  1;	///< Required element.
/// Element FaultCode of type "urn:dslforum-org:cwmp-1-1":FaultCodeType.
    cwmp1__FaultCodeType                 FaultCode                      1;	///< Required element.
/// Element FaultString of type xs:string.
    char*                                FaultString                    0;	///< Optional element.
    }                                   *SetParameterValuesFault        0;
};


/// Element "urn:dslforum-org:cwmp-1-1":GetRPCMethods of complexType.
/// @brief GeRPCMethods message - Annex A.3.1.1

/// "urn:dslforum-org:cwmp-1-1":GetRPCMethods is a complexType.
struct _cwmp1__GetRPCMethods
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetRPCMethodsResponse of complexType.
/// @brief GeRPCMethodsResponse message - Annex A.3.1.1

/// "urn:dslforum-org:cwmp-1-1":GetRPCMethodsResponse is a complexType.
struct _cwmp1__GetRPCMethodsResponse
{
/// Element MethodList of type "urn:dslforum-org:cwmp-1-1":MethodList.
    struct cwmp1MethodList*              MethodList                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterValues of complexType.
/// @brief SetParameterValues message - Annex A.3.2.1

/// "urn:dslforum-org:cwmp-1-1":SetParameterValues is a complexType.
struct _cwmp1__SetParameterValues
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct cwmp1ParameterValueList*      ParameterList                  1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp1__ParameterKeyType              ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterValuesResponse of complexType.
/// @brief SetParameterValuesResponse message - Annex A.3.2.1

/// "urn:dslforum-org:cwmp-1-1":SetParameterValuesResponse is a complexType.
struct _cwmp1__SetParameterValuesResponse
{
    enum _cwmp1__SetParameterValuesResponse_Status
    {
/// @brief All Parameter changes have been validated and applied
	_cwmp1__SetParameterValuesResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief All Parameter changes have been validated and committed, but some or all are not yet applied (for example, if a reboot is required before the new values are applied)
	_cwmp1__SetParameterValuesResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterValues of complexType.
/// @brief GetParameterValues message - Annex A.3.2.2

/// "urn:dslforum-org:cwmp-1-1":GetParameterValues is a complexType.
struct _cwmp1__GetParameterValues
{
/// Element ParameterNames of type "urn:dslforum-org:cwmp-1-1":ParameterNames.
    struct cwmp1ParameterNames*          ParameterNames                 1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterValuesResponse of complexType.
/// @brief GetParameterValuesResponse message - Annex A.3.2.2

/// "urn:dslforum-org:cwmp-1-1":GetParameterValuesResponse is a complexType.
struct _cwmp1__GetParameterValuesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct cwmp1ParameterValueList*      ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterNames of complexType.
/// @brief GetParameterNames message - Annex A.3.2.3

/// "urn:dslforum-org:cwmp-1-1":GetParameterNames is a complexType.
struct _cwmp1__GetParameterNames
{
/// Length of this string is within 0..256 characters
    char*                                                              
                                        *ParameterPath                 ;	///< Nullable pointer.
/// Element NextLevel of type xs:boolean.
    enum xsd__boolean                    NextLevel                      1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterNamesResponse of complexType.
/// @brief GetParameterNamesResponse message - Annex A.3.2.3

/// "urn:dslforum-org:cwmp-1-1":GetParameterNamesResponse is a complexType.
struct _cwmp1__GetParameterNamesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterInfoList.
    struct cwmp1ParameterInfoList*       ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterAttributes of complexType.
/// @brief SetParameterAttributes message - Annex A.3.2.4

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributes is a complexType.
struct _cwmp1__SetParameterAttributes
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":SetParameterAttributesList.
    struct cwmp1SetParameterAttributesList*  ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetParameterAttributesResponse of complexType.
/// @brief SetParameterAttributesResponse message - Annex A.3.2.4

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesResponse is a complexType.
struct _cwmp1__SetParameterAttributesResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterAttributes of complexType.
/// @brief GetParameterAttributes message - Annex A.3.2.5

/// "urn:dslforum-org:cwmp-1-1":GetParameterAttributes is a complexType.
struct _cwmp1__GetParameterAttributes
{
/// Element ParameterNames of type "urn:dslforum-org:cwmp-1-1":ParameterNames.
    struct cwmp1ParameterNames*          ParameterNames                 1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetParameterAttributesResponse of complexType.
/// @brief GetParameterAttributesResponse message - Annex A.3.2.5

/// "urn:dslforum-org:cwmp-1-1":GetParameterAttributesResponse is a complexType.
struct _cwmp1__GetParameterAttributesResponse
{
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterAttributeList.
    struct cwmp1ParameterAttributeList*  ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AddObject of complexType.
/// @brief AddObject message - Annex A.3.2.6

/// "urn:dslforum-org:cwmp-1-1":AddObject is a complexType.
struct _cwmp1__AddObject
{
/// Element ObjectName of type "urn:dslforum-org:cwmp-1-1":ObjectNameType.
    cwmp1__ObjectNameType                ObjectName                     1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp1__ParameterKeyType              ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AddObjectResponse of complexType.
/// @brief AddObjectResponse message - Annex A.3.2.6

/// "urn:dslforum-org:cwmp-1-1":AddObjectResponse is a complexType.
struct _cwmp1__AddObjectResponse
{
/// Value range is [1..]
    unsigned int                                                       
                                         InstanceNumber                 1;	///< Required element.
    enum _cwmp1__AddObjectResponse_Status
    {
/// @brief The object has been created
	_cwmp1__AddObjectResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief The object creation has been validated and committed, but not yet applied
	_cwmp1__AddObjectResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DeleteObject of complexType.
/// @brief DeleteObject message - Annex A.3.2.7

/// "urn:dslforum-org:cwmp-1-1":DeleteObject is a complexType.
struct _cwmp1__DeleteObject
{
/// Element ObjectName of type "urn:dslforum-org:cwmp-1-1":ObjectNameType.
    cwmp1__ObjectNameType                ObjectName                     1;	///< Required element.
/// Element ParameterKey of type "urn:dslforum-org:cwmp-1-1":ParameterKeyType.
    cwmp1__ParameterKeyType              ParameterKey                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DeleteObjectResponse of complexType.
/// @brief DeleteObjectResponse message - Annex A.3.2.7

/// "urn:dslforum-org:cwmp-1-1":DeleteObjectResponse is a complexType.
struct _cwmp1__DeleteObjectResponse
{
    enum _cwmp1__DeleteObjectResponse_Status
    {
/// @brief The object has been deleted
	_cwmp1__DeleteObjectResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief The object deletion has been validated and committed, but not yet applied
	_cwmp1__DeleteObjectResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Download of complexType.
/// @brief Download message - Annex A.3.2.8

/// "urn:dslforum-org:cwmp-1-1":Download is a complexType.
struct _cwmp1__Download
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         URL                            1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Username                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Password                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         SuccessURL                     1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         FailureURL                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":DownloadResponse of complexType.
/// @brief DownloadResponse message - Annex A.3.2.8

/// "urn:dslforum-org:cwmp-1-1":DownloadResponse is a complexType.
struct _cwmp1__DownloadResponse
{
    enum _cwmp1__DownloadResponse_Status
    {
/// @brief Download has completed and been applied
	_cwmp1__DownloadResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief Download has not yet been completed and applied
	_cwmp1__DownloadResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Reboot of complexType.
/// @brief Reboot message - Annex A.3.2.9

/// "urn:dslforum-org:cwmp-1-1":Reboot is a complexType.
struct _cwmp1__Reboot
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RebootResponse of complexType.
/// @brief RebootResponse message - Annex A.3.2.9

/// "urn:dslforum-org:cwmp-1-1":RebootResponse is a complexType.
struct _cwmp1__RebootResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetQueuedTransfers of complexType.
/// @brief GetQueuedTransfers message - Annex A.4.1.1

/// "urn:dslforum-org:cwmp-1-1":GetQueuedTransfers is a complexType.
struct _cwmp1__GetQueuedTransfers
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetQueuedTransfersResponse of complexType.
/// @brief GetQueuedTransfersResponse message - Annex A.4.1.1

/// "urn:dslforum-org:cwmp-1-1":GetQueuedTransfersResponse is a complexType.
struct _cwmp1__GetQueuedTransfersResponse
{
/// Element TransferList of type "urn:dslforum-org:cwmp-1-1":TransferList.
    struct cwmp1TransferList*            TransferList                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":ScheduleInform of complexType.
/// @brief ScheduleInform message - Annex A.4.1.2

/// "urn:dslforum-org:cwmp-1-1":ScheduleInform is a complexType.
struct _cwmp1__ScheduleInform
{
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":ScheduleInformResponse of complexType.
/// @brief ScheduleInformResponse message - Annex A.4.1.2

/// "urn:dslforum-org:cwmp-1-1":ScheduleInformResponse is a complexType.
struct _cwmp1__ScheduleInformResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":SetVouchers of complexType.
/// @brief SetVouchers message - Annex A.4.1.3

/// "urn:dslforum-org:cwmp-1-1":SetVouchers is a complexType.
struct _cwmp1__SetVouchers
{
/// Element VoucherList of type "urn:dslforum-org:cwmp-1-1":VoucherList.
    struct cwmp1VoucherList*             VoucherList                    1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":SetVouchersResponse of complexType.
/// @brief SetVouchersResponse message - Annex A.4.1.3

/// "urn:dslforum-org:cwmp-1-1":SetVouchersResponse is a complexType.
struct _cwmp1__SetVouchersResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetOptions of complexType.
/// @brief GetOptions message - Annex A.4.1.4

/// "urn:dslforum-org:cwmp-1-1":GetOptions is a complexType.
struct _cwmp1__GetOptions
{
/// Length of this string is within 0..64 characters
    char*                                                              
                                         OptionName                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":GetOptionsResponse of complexType.
/// @brief GetOptionsResponse message - Annex A.4.1.4

/// "urn:dslforum-org:cwmp-1-1":GetOptionsResponse is a complexType.
struct _cwmp1__GetOptionsResponse
{
/// Element OptionList of type "urn:dslforum-org:cwmp-1-1":OptionList.
    struct cwmp1OptionList*              OptionList                     1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Upload of complexType.
/// @brief Upload message - Annex A.4.1.5

/// "urn:dslforum-org:cwmp-1-1":Upload is a complexType.
struct _cwmp1__Upload
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Vendor Configuration File"
/// Content pattern is "2 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         URL                            1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Username                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Password                       1;	///< Required element.
/// Element DelaySeconds of type xs:unsignedInt.
    unsigned int                         DelaySeconds                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":UploadResponse of complexType.
/// @brief UploadResponse message - Annex A.4.1.5

/// "urn:dslforum-org:cwmp-1-1":UploadResponse is a complexType.
struct _cwmp1__UploadResponse
{
    enum _cwmp1__UploadResponse_Status
    {
/// @brief Upload has been completed
	_cwmp1__UploadResponse_Status__0 = 0,	///< xs:int value="0"
/// @brief Upload has not yet completed
	_cwmp1__UploadResponse_Status__1 = 1,	///< xs:int value="1"
    }
                                         Status                         1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":FactoryReset of complexType.
/// @brief FactoryReset message - Annex A.4.1.6

/// "urn:dslforum-org:cwmp-1-1":FactoryReset is a complexType.
struct _cwmp1__FactoryReset
{
};


/// Element "urn:dslforum-org:cwmp-1-1":FactoryResetResponse of complexType.
/// @brief FactoryResetResponse message - Annex A.4.1.6

/// "urn:dslforum-org:cwmp-1-1":FactoryResetResponse is a complexType.
struct _cwmp1__FactoryResetResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfers of complexType.
/// @brief GetAllQueuedTransfers message - Annex A.4.1.7

/// "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfers is a complexType.
struct _cwmp1__GetAllQueuedTransfers
{
};


/// Element "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfersResponse of complexType.
/// @brief GetAllQueuedTransfersResponse message - Annex A.4.1.7

/// "urn:dslforum-org:cwmp-1-1":GetAllQueuedTransfersResponse is a complexType.
struct _cwmp1__GetAllQueuedTransfersResponse
{
/// Element TransferList of type "urn:dslforum-org:cwmp-1-1":AllTransferList.
    struct cwmp1AllTransferList*         TransferList                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":Inform of complexType.
/// @brief Inform message - Annex A.3.3.1

/// "urn:dslforum-org:cwmp-1-1":Inform is a complexType.
struct _cwmp1__Inform
{
/// Element DeviceId of type "urn:dslforum-org:cwmp-1-1":DeviceIdStruct.
    struct cwmp1__DeviceIdStruct*        DeviceId                       1;	///< Required element.
/// Element Event of type "urn:dslforum-org:cwmp-1-1":EventList.
    struct cwmp1EventList*               Event                          1;	///< Required element.
/// Element MaxEnvelopes of type xs:unsignedInt.
    unsigned int                         MaxEnvelopes                   1;	///< Required element.
/// Element CurrentTime of type xs:dateTime.
    time_t                               CurrentTime                    1;	///< Required element.
/// Element RetryCount of type xs:unsignedInt.
    unsigned int                         RetryCount                     1;	///< Required element.
/// Element ParameterList of type "urn:dslforum-org:cwmp-1-1":ParameterValueList.
    struct cwmp1ParameterValueList*      ParameterList                  1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":InformResponse of complexType.
/// @brief InformResponse message - Annex A.3.3.1

/// "urn:dslforum-org:cwmp-1-1":InformResponse is a complexType.
struct _cwmp1__InformResponse
{
/// Element MaxEnvelopes of type xs:unsignedInt.
    unsigned int                         MaxEnvelopes                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":TransferComplete of complexType.
/// @brief TransferComplete message - Annex A.3.3.2

/// "urn:dslforum-org:cwmp-1-1":TransferComplete is a complexType.
struct _cwmp1__TransferComplete
{
/// Element CommandKey of type "urn:dslforum-org:cwmp-1-1":CommandKeyType.
    cwmp1__CommandKeyType                CommandKey                     1;	///< Required element.
/// Element FaultStruct of type "urn:dslforum-org:cwmp-1-1":FaultStruct.
    struct cwmp1__FaultStruct*           FaultStruct                    1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":TransferCompleteResponse of complexType.
/// @brief TransferCompleteResponse message - Annex A.3.3.2

/// "urn:dslforum-org:cwmp-1-1":TransferCompleteResponse is a complexType.
struct _cwmp1__TransferCompleteResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":AutonomousTransferComplete of complexType.
/// @brief AutonomousTransferComplete message - Annex A.3.3.3

/// "urn:dslforum-org:cwmp-1-1":AutonomousTransferComplete is a complexType.
struct _cwmp1__AutonomousTransferComplete
{
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         AnnounceURL                    1;	///< Required element.
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         TransferURL                    1;	///< Required element.
/// Element IsDownload of type xs:boolean.
    enum xsd__boolean                    IsDownload                     1;	///< Required element.
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "4 Vendor Log File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileSize of type xs:unsignedInt.
    unsigned int                         FileSize                       1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         TargetFileName                 1;	///< Required element.
/// Element FaultStruct of type "urn:dslforum-org:cwmp-1-1":FaultStruct.
    struct cwmp1__FaultStruct*           FaultStruct                    1;	///< Required element.
/// Element StartTime of type xs:dateTime.
    time_t                               StartTime                      1;	///< Required element.
/// Element CompleteTime of type xs:dateTime.
    time_t                               CompleteTime                   1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":AutonomousTransferCompleteResponse of complexType.
/// @brief AutonomousTransferCompleteResponse message - Annex A.3.3.3

/// "urn:dslforum-org:cwmp-1-1":AutonomousTransferCompleteResponse is a complexType.
struct _cwmp1__AutonomousTransferCompleteResponse
{
};


/// Element "urn:dslforum-org:cwmp-1-1":Kicked of complexType.
/// @brief Kicked message - Annex A.4.2.1

/// "urn:dslforum-org:cwmp-1-1":Kicked is a complexType.
struct _cwmp1__Kicked
{
/// Length of this string is within 0..32 characters
    char*                                                              
                                         Command                        1;	///< Required element.
/// Length of this string is within 0..64 characters
    char*                                                              
                                         Referer                        1;	///< Required element.
/// Length of this string is within 0..256 characters
    char*                                                              
                                         Arg                            1;	///< Required element.
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         Next                           1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":KickedResponse of complexType.
/// @brief KickedResponse message - Annex A.4.2.1

/// "urn:dslforum-org:cwmp-1-1":KickedResponse is a complexType.
struct _cwmp1__KickedResponse
{
/// Length of this string is within 0..1024 characters
    char*                                                              
                                         NextURL                        1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RequestDownload of complexType.
/// @brief RequestDownload message - Annex A.4.2.2

/// "urn:dslforum-org:cwmp-1-1":RequestDownload is a complexType.
struct _cwmp1__RequestDownload
{
/// Length of this string is within 0..64 characters
/// Content pattern is "1 Firmware Upgrade Image"
/// Content pattern is "2 Web Content"
/// Content pattern is "3 Vendor Configuration File"
/// Content pattern is "X [0-9A-F]{6} .*"
    char*                                                              
                                         FileType                       1;	///< Required element.
/// Element FileTypeArg of type "urn:dslforum-org:cwmp-1-1":FileTypeArg.
    struct cwmp1FileTypeArg*             FileTypeArg                    1;	///< Required element.
};


/// Element "urn:dslforum-org:cwmp-1-1":RequestDownloadResponse of complexType.
/// @brief RequestDownloadResponse message - Annex A.4.2.2

/// "urn:dslforum-org:cwmp-1-1":RequestDownloadResponse is a complexType.
struct _cwmp1__RequestDownloadResponse
{
};

/// "urn:dslforum-org:cwmp-1-1":MethodList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct cwmp1MethodList
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":EventList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":EventStruct
struct cwmp1EventList
{
/// Pointer to array of struct cwmp1__EventStruct*.
    struct cwmp1__EventStruct*          *__ptrEventStruct              ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterValueList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterValueStruct
struct cwmp1ParameterValueList
{
/// Pointer to array of struct cwmp1__ParameterValueStruct*.
    struct cwmp1__ParameterValueStruct* *__ptrParameterValueStruct     ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterInfoList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterInfoStruct
struct cwmp1ParameterInfoList
{
/// Pointer to array of struct cwmp1__ParameterInfoStruct*.
    struct cwmp1__ParameterInfoStruct*  *__ptrParameterInfoStruct      ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterNames is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct cwmp1ParameterNames
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":AccessList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct cwmp1AccessList
{
/// Pointer to array of char*.
    char*                               *__ptrstring                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":SetParameterAttributesList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":SetParameterAttributesStruct
struct cwmp1SetParameterAttributesList
{
/// Pointer to array of struct cwmp1__SetParameterAttributesStruct*.
    struct cwmp1__SetParameterAttributesStruct* *__ptrSetParameterAttributesStruct;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":ParameterAttributeList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ParameterAttributeStruct
struct cwmp1ParameterAttributeList
{
/// Pointer to array of struct cwmp1__ParameterAttributeStruct*.
    struct cwmp1__ParameterAttributeStruct* *__ptrParameterAttributeStruct ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":TransferList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":QueuedTransferStruct
struct cwmp1TransferList
{
/// Pointer to array of struct cwmp1__QueuedTransferStruct*.
    struct cwmp1__QueuedTransferStruct* *__ptrQueuedTransferStruct     ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":AllTransferList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":AllQueuedTransferStruct
struct cwmp1AllTransferList
{
/// Pointer to array of struct cwmp1__AllQueuedTransferStruct*.
    struct cwmp1__AllQueuedTransferStruct* *__ptrAllQueuedTransferStruct  ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":VoucherList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of SOAP-ENC:base64
struct cwmp1VoucherList
{
/// Pointer to array of struct SOAP_ENC__base64*.
    struct SOAP_ENC__base64*            *__ptrbase64                   ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":OptionList is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":OptionStruct
struct cwmp1OptionList
{
/// Pointer to array of struct cwmp1__OptionStruct*.
    struct cwmp1__OptionStruct*         *__ptrOptionStruct             ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dslforum-org:cwmp-1-1":FileTypeArg is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "urn:dslforum-org:cwmp-1-1":ArgStruct
struct cwmp1FileTypeArg
{
/// Pointer to array of struct cwmp1__ArgStruct*.
    struct cwmp1__ArgStruct*            *__ptrArgStruct                ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};


/// Element "urn:dslforum-org:cwmp-1-1":ID of complexType.

/// "urn:dslforum-org:cwmp-1-1":ID is a complexType with simpleContent.
struct _cwmp1__ID
{
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference SOAP-ENV:mustUnderstand.
   @char*                                SOAP_ENV__mustUnderstand       1;	///< Fixed value="1".
};


/// Element "urn:dslforum-org:cwmp-1-1":HoldRequests of complexType.

/// "urn:dslforum-org:cwmp-1-1":HoldRequests is a complexType with simpleContent.
struct _cwmp1__HoldRequests
{
/// __item wraps 'xs:boolean' simpleContent.
    enum xsd__boolean                    __item                        ;
/// Imported attribute reference SOAP-ENV:mustUnderstand.
   @char*                                SOAP_ENV__mustUnderstand       1;	///< Fixed value="1".
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap cwmp1 service name:	cwmpBinding 
//gsoap cwmp1 service type:	cwmpPortType 
//gsoap cwmp1 service port:	http://192.168.2.30:8080/openacs/acs 
//gsoap cwmp1 service namespace:	urn:dslforum-org:cwmp-1-1 
//gsoap cwmp1 service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage cwmp Definitions

@section cwmp_bindings Bindings
  - @ref cwmpBinding

*/

/**

@page cwmpBinding Binding "cwmpBinding"

@section cwmpService_service Service Documentation "cwmpService"
Metanoia cwmp service definition

@section cwmpBinding_operations Operations of Binding  "cwmpBinding"
  - @ref cwmp1__Inform

@section cwmpBinding_ports Endpoints of Binding  "cwmpBinding"
  - http://192.168.2.30:8080/openacs/acs

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * cwmpBinding                                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * cwmp1__Inform                                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "cwmp1__Inform" of service binding "cwmpBinding"

/**

Operation details:

Service definition of function GetRPCMethods
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_cwmp1__Inform(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct cwmp1__DeviceIdStruct*       DeviceId,
    struct cwmp1EventList*              Event,
    unsigned int                        MaxEnvelopesI,
    time_t                              CurrentTime,
    unsigned int                        RetryCount,
    struct cwmp1ParameterValueList*     ParameterList,
    // response parameters:
    unsigned int                       *MaxEnvelopesO
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int cwmp1__Inform(
    struct soap *soap,
    // request parameters:
    struct cwmp1__DeviceIdStruct*       DeviceId,
    struct cwmp1EventList*              Event,
    unsigned int                        MaxEnvelopesI,
    time_t                              CurrentTime,
    unsigned int                        RetryCount,
    struct cwmp1ParameterValueList*     ParameterList,
    // response parameters:
    unsigned int                       *MaxEnvelopesO
  );
@endcode

*/

//gsoap cwmp1 service method-style:	Inform rpc
//gsoap cwmp1 service method-encoding:	Inform http://schemas.xmlsoap.org/soap/encoding/
//gsoap cwmp1 service method-action:	Inform ""
int cwmp1__Inform(
    struct cwmp1__DeviceIdStruct*       DeviceId,	///< Request parameter
    struct cwmp1EventList*              Event,	///< Request parameter
    unsigned int                        MaxEnvelopesI,	///< Request parameter
    time_t                              CurrentTime,	///< Request parameter
    unsigned int                        RetryCount,	///< Request parameter
    struct cwmp1ParameterValueList*     ParameterList,	///< Request parameter
    unsigned int                       *MaxEnvelopesO	///< Response parameter
);

/* End of cwmp-1-1.h */
