#!/bin/sh
# Copyright (C) 2012 Luka Perkov <freecwmp@lukaperkov.net>
# Copyright (C) 2012 Ahmed Zribi <ahmed.zribi@pivasoftware.com>

get_wlan_enable() {
local num="$1"
local type="xsd:boolean"
local val=""
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-device[$num].disabled 2> /dev/null`
	let num=$num+1
	if [ "$val" = "1" ]; then
		val="0"
	else
		val="1"
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Enable" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Enable" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Enable"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Enable" "$val"
	;;
esac
}

set_wlan_enable() {
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "1" ]; then
		val="0"
	else
		val="1"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-device[$num].disabled="$val"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Enable"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_status() {
local num="$1"
local type="xsd:string"
local val=""
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-device[$num].disabled 2> /dev/null`
	let num=$num+1
	if [ "$val" = "1" ]; then
		val="Disabled"
	else
		val="Up"
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Status" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="0"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Status" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Status"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Status" "$val"
	;;
esac
}

get_wlan_bssid() {
local num="$1"
local type="xsd:string"
local val=""
local permissions=""
case "$action" in
	get_value)
	device=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].device 2> /dev/null`
	let num=$num+1
	json_load "$(devstatus $device)"
	json_get_var macaddr macaddr
	val="$macaddr"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BSSID" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="0"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BSSID" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BSSID"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BSSID" "$val"
	;;
esac
}

get_wlan_ssid() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/wlc ssid`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.SSID" "$val"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.SSID" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.SSID"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.SSID" "$val"
	;;
esac

}

set_wlan_ssid() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].ssid="$val"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.SSID"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_channel() {
local num="$1"
local type="xsd:string"
local val=""
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/wlc channel`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Channel" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Channel" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Channel"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Channel" "$val"
	;;
esac
}

set_wlan_channel() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].channel="$val"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.Channel"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_mac_control_enable() {
local num="$1"
local type="xsd:boolean"
local val=""
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-device[$num].macfilter 2> /dev/null`
	let num=$num+1
	if [ "$val" = "2" ]; then
		val="1"
	else
		val="0"
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled" "$val"
	;;
esac
}

set_wlan_mac_control_enable() {
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "1" ]; then
		val="2"
	else
		val="0"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-device[$num].macfilter="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled"
	freecwmp_notify "$parm" "$2" "xsd:boolean"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.MACAddressControlEnabled"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_wep_key_index() {
local num="$1"
local val=""
local type="xsd:unsignedInt"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].key`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex" "$val"
	;;
esac
}

set_wlan_wep_key_index() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].key="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex"
	freecwmp_notify "$parm" "$2" "xsd:unsignedInt"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WEPKeyIndex"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_basic_encryption_modes() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	wep=`/usr/sbin/wlctl -i wl$num wepstatus`
	let num=$num+1
	if [ "$wep" = "1" ]; then
		val="WEPEncryption"
	else
		val="None"
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes" "$val"
	;;
esac
}

set_wlan_basic_encryption_modes() {
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "WEPEncryption" ]; then
		val="wep-open"
	elif [ "$val" = "None" ]; then
		val="0"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicEncryptionModes"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_basic_authentication_mode() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	wep=`/usr/sbin/wlctl -i wl$num wepstatus`
	auth=`/usr/sbin/wlctl -i wl$num auth`
	let num=$num+1
	if [ "$wep" = "1" -a "$auth" = "1" ]; then
		val="SharedAuthentication"
	else
		val="None"
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode" "$val"
	;;
esac
}

set_wlan_basic_authentication_mode() {
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "WEPEncryption" ]; then
		val="wep-shared"
	elif [ "$val" = "None" ]; then
		val="0"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.BasicAuthenticationMode"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_wpa_encryption_modes() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	#TKIPEncryption, AESEncryption, TKIPandAESEncryption
	value=`/usr/sbin/wlctl -i wl$num wpa_auth | awk -F' ' '{print$1}'`
	wpa=`echo $(($value))`
	encryption=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].encryption`
	let num=$num+1
	if [ "$wpa" = "4" -o "$wpa" = "132" ]; then
		if [ "$encryption" = "psk+tkip" -o "$encryption" = "pskmixedpsk2+tkip" ];then
			val="TKIPEncryption"
		elif [ "$encryption" = "psk+ccmp" -o "$encryption" = "pskmixedpsk2+ccmp" ];then
			val="AESEncryption"
		elif [ "$encryption" = "psk+tkip+ccmp" -o "$encryption" = "pskmixedpsk2+tkip+ccmp"  ];then
			val="TKIPandAESEncryption"
		fi
	else
		val=""
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes" "$val"
	;;
esac
}

set_wlan_wpa_encryption_modes()
{
local num="$1"
local val="$2"
case $action in
	set_value)
	#TKIPEncryption, AESEncryption, TKIPandAESEncryption
	if [ "$val" = "TKIPEncryption" ]; then
		val="psk+tkip"
	elif [ "$val" = "AESEncryption" ]; then
		val="psk+ccmp"
	elif [ "$val" = "TKIPandAESEncryption" ]; then
		val="psk+tkip+ccmp"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAEncryptionModes"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_wpa_authentication_mode() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	value=`/usr/sbin/wlctl -i wl$num wpa_auth | awk -F' ' '{print$1}'`
	wpa=`echo $(($value))`
	let num=$num+1
	if [ "$wpa" = "4" -o "$wpa" = "66" ]; then
			val="PSKAuthentication"
	elif [ "$wpa" = "2" ];then
			val="EAPAuthentication"
	else
		val=""
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode" "$val"
	;;
esac
}

set_wlan_wpa_authentication_mode()
{
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "PSKAuthentication" -o "$wpa" = "132" ]; then
		val="psk"
	elif [ "$val" = "EAPAuthentication" -o "$wpa" = "66" ]; then
		val="wpa"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.WPAAuthenticationMode"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_ieee_11i_encryption_modes()
{
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	#TKIPEncryption, AESEncryption, TKIPandAESEncryption
	value=`/usr/sbin/wlctl -i wl$num wpa_auth | awk -F' ' '{print$1}'`
	wpa=`echo $(($value))`
	encryption=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].encryption`
	let num=$num+1
	if [ "$wpa" = "128" -o "$wpa" = "132" ]; then
		if [ "$encryption" = "psk2+tkip" -o "$encryption" = "pskmixedpsk2+tkip" ];then
			val="TKIPEncryption"
		elif [ "$encryption" = "psk2+ccmp" -o "$encryption" = "pskmixedpsk2+ccmp" ];then
			val="AESEncryption"
		elif [ "$encryption" = "psk2+tkip+ccmp" -o "$encryption" = "pskmixedpsk2+tkip+ccmp" ];then
			val="TKIPandAESEncryption"
		fi
	else
		val=""
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes" "$val"
	;;
esac
}

set_wlan_ieee_11i_encryption_modes()
{
local num="$1"
local val="$2"
case $action in
	set_value)
	#TKIPEncryption, AESEncryption, TKIPandAESEncryption
	if [ "$val" = "TKIPEncryption" ]; then
		val="psk2+tkip"
	elif [ "$val" = "AESEncryption" ]; then
		val="psk2+ccmp"
	elif [ "$val" = "TKIPandAESEncryption" ]; then
		val="psk2+tkip+ccmp"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iEncryptionModes"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_ieee_11i_authentication_mode() {
local num="$1"
local val=""
local permissions=""
case "$action" in
	get_value)
	value=`/usr/sbin/wlctl -i wl$num wpa_auth | awk -F' ' '{print$1}'`
	wpa=`echo $(($value))`
	let num=$num+1
	if [ "$wpa" = "128" -o "$wpa" = "132" ]; then
			val="PSKAuthentication"
	elif [ "$wpa" = "64" -o "$wpa" = "66" ];then
			val="EAPAuthentication"
	else
		val=""
	fi
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode" "$val" "$permissions"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode" "$val"
	;;
esac
}

set_wlan_ieee_11i_authentication_mode() {
local num="$1"
local val="$2"
case $action in
	set_value)
	if [ "$val" = "PSKAuthentication" ]; then
		val="psk2"
	elif [ "$val" = "EAPAuthentication" ]; then
		val="wpa2"
	fi
	delay_command "wifi" "wifi" "45"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set wireless.@wifi-iface[$num].encryption="$val"
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode"
	freecwmp_notify "$parm" "$2" "xsd:string"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.IEEE11iAuthenticationMode"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_radio_enabled() {
local num="$1"
local val=""
local type="xsd:boolean"
local permissions=""
case "$action" in
	get_value)
	radio=`/usr/sbin/wlctl -i wl$num radio`
	val=`echo $(($radio))`
	if [ "$val" = "0" ];then
		val=1
	elif [ "$val" = "1" ];then
		val=0
	fi
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled" "$val"
	;;
esac
}

set_wlan_radio_enabled() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	if [ "$val" = "0" ];then
		val="off"
	elif [ "$val" = "1" ];then
		val="on"
	fi
	/usr/sbin/wlctl -i wl$num radio $val
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled"
	freecwmp_notify "$parm" "$2" "xsd:boolean"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.RadioEnabled"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_device_operation_mode() {
local num="$1"
local val=""
local type="xsd:boolean"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].mode`
	if [ "$val" = "ap" ];then
		val="InfrastructureAccessPoint"
	elif [ "$val" = "wds" ];then
		val="WirelessRepeater"
	fi
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode" "$val"
	;;
esac
}

set_wlan_device_operation_mode() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	if [ "$val" = "InfrastructureAccessPoint" ];then
		/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].mode="ap"
	elif [ "$val" = "WirelessRepeaterwds" ];then
		/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].mode="wds"
	fi
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode"
	freecwmp_notify "$parm" "$2" "xsd:boolean"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.DeviceOperationMode"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_authentication_service_mode() {
local num="$1"
local val=""
local type="xsd:boolean"
local permissions=""
case "$action" in
	get_value)
	2/64/66
	value=`/usr/sbin/wlctl -i wl$num wpa_auth | awk -F' ' '{print$1}'`
	wpa=`echo $(($value))`
	if [ "$wpa" = "2" -o "$wpa" = "64" -o "$wpa" = "66" ]; then
		val="RadiusClient"
	else
		val="None"
	fi
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode" "$val"
	;;
esac
}

set_wlan_authentication_service_mode() {
local num="$1"
local val="$2"
case $action in
	set_value)
	delay_command "wifi" "wifi" "45"
	if [ "$val" = "None" ];then
		/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].encryption="psk"
	elif [ "$val" = "RadiusClient" ];then
		/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get wireless.@wifi-iface[$num].encryption="wpa"
	fi
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode"
	freecwmp_notify "$parm" "$2" "xsd:boolean"
	;;
	set_notification)
	let num=$num+1
	local parm="InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AuthenticationServiceMode"
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wlan_total_associations() {
local num="$1"
local val=""
local type="xsd:unsignedInt"
local permissions=""
case "$action" in
	get_value)
	val=`/usr/sbin/wlctl -i wl$num assoclist | grep -c 'assoclist'`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations" "$val" "$permissions" "$type"
	;;
	get_name)
	permissions="1"
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations" "$val" "$permissions"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations" "$val"
	;;
esac
}

get_wlan_associated_device() {
local num="$1"
local val=""
local permissions=""
local i=0
local assoclist=`/usr/sbin/wlctl -i wl$num assoclist|awk -F' ' '{print $2}'`
let num=$num+1
case "$action" in
	get_value)
	for mac in $assoclist;do
		let i=$i+1
		mac_lower=`echo $mac|tr '[A-F]' '[a-f]'`
		ip=`cat /proc/net/arp|grep $mac_lower|awk -F' ' '{print $1}'`
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceMACAddress" "$mac" "$permissions"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceIPAddress" "$ip" "$permissions"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceAuthenticationState" "$ip" "$permissions" "xsd:boolean"
	done
	;;
	get_name)
	for mac in $assoclist;do
		let i=$i+1
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceMACAddress" "" "0"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceIPAddress" "" "0"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceAuthenticationState" "" "0"
	done
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.TotalAssociations" "$val"
	for mac in $assoclist;do
		let i=$i+1
		freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceMACAddress"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceMACAddress" "$val"
		freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceIPAddress"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceIPAddress" "$val"
		freecwmp_get_parameter_notification "val" "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceAuthenticationState"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.$num.AssociatedDevice.$i.AssociatedDeviceAuthenticationState" "$val"
	done
	;;
esac
}

add_ip_interface() {
	local i=0
	local instance=0
	while [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance 2>/dev/null`" != "" ] ;do
		instance=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance 2>/dev/null`
		let i=$i+1
	done
	let instance=$instance+1
	freecwmp_add_lan_device_ip_interface "$1$instance." "$instance"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q commit
	freecwmp_output "" "" "" "" "" "0" "$instance"
}

get_ip_interface() {
local i=0
while [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get cwmp.@object[$i].parameter 2>/dev/null`" != "" ]
do
	if [ "$action" = "get_name" ];then
			let i=$i+1
			local parm=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`
			permissions="1"
			freecwmp_output "$parm" "" "$permissions"
	fi
done
}

get_ip_interface_ip_address() {
local val=""
local permissions=""
local i=0
while [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "" ]
do
	local parm=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`
	local indice=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance 2>/dev/null`
	case "$action" in
		get_value)
		val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get network.lan$indice.ipaddr 2> /dev/null`
		freecwmp_output $parm"IPInterfaceIPAddress" "$val"
		;;
		get_name)
		permissions="1"
		freecwmp_output $parm"IPInterfaceIPAddress" "" "$permissions"
		;;
	esac
	let i=$i+1
done
}

set_ip_interface_ip_address() {
	local i=0
	local indice
	local _parm="$1"
	local ipaddr="$2"
	_parm="${_parm%.*}."
	while [ \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "$_parm" \) -a \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "" \) ]
	do
		let i=$i+1
	done
	if [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" = "" ]; then
		return $FAULT_CPE_INVALID_PARAMETER_NAME
	fi
	local indice=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance`
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set network.lan$indice.ipaddr=$ipaddr
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set network.lan$indice.proto=static
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q commit
	return $FAULT_CPE_NO_FAULT
}

get_ip_interface_netmask() {
local val=""
local permissions=""
local i=0
while [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "" ]
do
	local parm=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`
	local indice=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance 2>/dev/null`
	case "$action" in
		get_value)
		val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get network.lan$indice.netmask 2> /dev/null`
		freecwmp_output $parm"IPInterfaceSubnetMask" "$val"
		;;
		get_name)
		permissions="1"
		freecwmp_output $parm"IPInterfaceSubnetMask" "" "$permissions"
		;;
	esac
	let i=$i+1
done
}

set_ip_interface_netmask() {
	local i=0
	local indice
	local _parm="$1"
	local netmask="$2"
	_parm="${_parm%.*}."
	while [ \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "$_parm" \) -a \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "" \) ]
	do
		let i=$i+1
	done
	if [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" = "" ]; then
		return $FAULT_CPE_INVALID_PARAMETER_NAME
	fi
	local indice=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].instance`
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q set network.lan$indice.netmask=$netmask
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q commit
	return $FAULT_CPE_NO_FAULT
}

delete_ip_interface() {
	local indice=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$1].instance`
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q delete cwmp.@object[$1]
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q delete network.lan$indice
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q commit
	freecwmp_output "" "" "" "" "" "0"
}

add_lan_device() {
case "$1" in
	InternetGatewayDevice.LANDevice.1.LANHostConfigManagement.IPInterface.)
	add_ip_interface $1
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_lan_device() {
local _parm="$1"
local i=0
while [ \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "$_parm" \) -a \( "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" != "" \) ]
do
	let i=$i+1
done
if [ "`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -q get cwmp.@object[$i].parameter 2>/dev/null`" = "" ]; then
	return $FAULT_CPE_INVALID_PARAMETER_NAME
fi
case "${_parm%.*.}." in
	InternetGatewayDevice.LANDevice.1.LANHostConfigManagement.IPInterface.)
	delete_ip_interface $i
	return $FAULT_CPE_NO_FAULT
	;;
esac
}

get_lan_device() {
case "$1" in
	InternetGatewayDevice.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.LANHostConfigManagement.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.LANHostConfigManagement.IPInterface.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.LANHostConfigManagement.IPInterface.[1-9]+.)
	get_ip_interface_ip_address
	get_ip_interface_netmask
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable)
	get_wlan_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Status)
	get_wlan_status 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BSSID)
	get_wlan_bssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel)
	get_wlan_channel 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID)
	get_wlan_ssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled)
	get_wlan_mac_control_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex)
	get_wlan_wep_key_index 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes)
	get_wlan_basic_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode)
	get_wlan_basic_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes)
	get_wlan_wpa_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode)
	get_wlan_wpa_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes)
	get_wlan_ieee_11i_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode)
	get_wlan_ieee_11i_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;	
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode)
	get_wlan_device_operation_mode 0
	return $FAULT_CPE_NO_FAULT
	;;	
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode)
	get_wlan_authentication_service_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled)
	get_wlan_radio_enabled 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.TotalAssociations)
	get_wlan_total_associations 0
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}

get_lan_device_name() {
case "$1" in
	InternetGatewayDevice.)
	freecwmp_output "InternetGatewayDevice.LANDevice." "" "1"
	if [ "$2" = "0" ]; then
		freecwmp_output "InternetGatewayDevice.LANDevice.1." "" "1"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "" "1"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "" "1"
		get_wlan_enable 0
		get_wlan_status 0
		get_wlan_bssid 0
		get_wlan_channel 0
		get_wlan_ssid 0
		get_wlan_mac_control_enable 0
		get_wlan_wep_key_index 0
		get_wlan_basic_encryption_modes 0
		get_wlan_basic_authentication_mode 0
		get_wlan_wpa_encryption_modes 0
		get_wlan_wpa_authentication_mode 0
		get_wlan_ieee_11i_encryption_modes 0
		get_wlan_ieee_11i_authentication_mode 0
		get_wlan_radio_enabled 0
		get_wlan_device_operation_mode 0
		get_wlan_authentication_service_mode 0
		get_wlan_total_associations 0
		get_wlan_associated_device 0
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.)
	freecwmp_output "InternetGatewayDevice.LANDevice." "" "1"
	freecwmp_output "InternetGatewayDevice.LANDevice.1." "" "1"
	if [ "$2" = "0" ]; then
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "" "1"
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "" "1"
		get_wlan_enable 0
		get_wlan_status 0
		get_wlan_bssid 0
		get_wlan_channel 0
		get_wlan_ssid 0
		get_wlan_mac_control_enable 0
		get_wlan_wep_key_index 0
		get_wlan_basic_encryption_modes 0
		get_wlan_basic_authentication_mode 0
		get_wlan_wpa_encryption_modes 0
		get_wlan_wpa_authentication_mode 0
		get_wlan_ieee_11i_encryption_modes 0
		get_wlan_ieee_11i_authentication_mode 0
		get_wlan_radio_enabled 0
		get_wlan_device_operation_mode 0
		get_wlan_authentication_service_mode 0
		get_wlan_total_associations 0
		get_wlan_associated_device 0
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.)
	freecwmp_output "InternetGatewayDevice.LANDevice.1." "" "1"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "" "1"
	if [ "$2" = "0" ]; then
		freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "" "1"
		get_wlan_enable 0
		get_wlan_status 0
		get_wlan_bssid 0
		get_wlan_channel 0
		get_wlan_ssid 0
		get_wlan_mac_control_enable 0
		get_wlan_wep_key_index 0
		get_wlan_basic_encryption_modes 0
		get_wlan_basic_authentication_mode 0
		get_wlan_wpa_encryption_modes 0
		get_wlan_wpa_authentication_mode 0
		get_wlan_ieee_11i_encryption_modes 0
		get_wlan_ieee_11i_authentication_mode 0
		get_wlan_radio_enabled 0
		get_wlan_device_operation_mode 0
		get_wlan_authentication_service_mode 0
		get_wlan_total_associations 0
		get_wlan_associated_device 0
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.)
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "" "1"
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "" "1"
	if [ "$2" = "0" ]; then
		get_wlan_enable 0
		get_wlan_status 0
		get_wlan_bssid 0
		get_wlan_channel 0
		get_wlan_ssid 0
		get_wlan_mac_control_enable 0
		get_wlan_wep_key_index 0
		get_wlan_basic_encryption_modes 0
		get_wlan_basic_authentication_mode 0
		get_wlan_wpa_encryption_modes 0
		get_wlan_wpa_authentication_mode 0
		get_wlan_ieee_11i_encryption_modes 0
		get_wlan_ieee_11i_authentication_mode 0
		get_wlan_radio_enabled 0
		get_wlan_device_operation_mode 0
		get_wlan_authentication_service_mode 0
		get_wlan_total_associations 0
		get_wlan_associated_device 0
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.)
	freecwmp_output "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "" "1"
	if [ "$2" = "0" ]; then
		get_wlan_enable 0
		get_wlan_status 0
		get_wlan_ssid 0
		get_wlan_channel 0
		get_wlan_bssid 0
		get_wlan_mac_control_enable 0
		get_wlan_wep_key_index 0
		get_wlan_basic_encryption_modes 0
		get_wlan_basic_authentication_mode 0
		get_wlan_wpa_encryption_modes 0
		get_wlan_wpa_authentication_mode 0
		get_wlan_ieee_11i_encryption_modes 0
		get_wlan_ieee_11i_authentication_mode 0
		get_wlan_radio_enabled 0
		get_wlan_device_operation_mode 0
		get_wlan_authentication_service_mode 0
		get_wlan_total_associations 0
		get_wlan_associated_device 0
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Status)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_status 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BSSID)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_bssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_channel 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_ssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_mac_control_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_wep_key_index 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_basic_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_basic_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_wpa_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_wpa_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_ieee_11i_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_ieee_11i_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_radio_enabled 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_device_operation_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_authentication_service_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.TotalAssociations)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_wlan_total_associations 0
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}

get_lan_device_notification() {
case "$1" in
	InternetGatewayDevice.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.)
	get_wlan_enable 0
	get_wlan_status 0
	get_wlan_bssid 0
	get_wlan_channel 0
	get_wlan_ssid 0
	get_wlan_mac_control_enable 0
	get_wlan_wep_key_index 0
	get_wlan_basic_encryption_modes 0
	get_wlan_basic_authentication_mode 0
	get_wlan_wpa_encryption_modes 0
	get_wlan_wpa_authentication_mode 0
	get_wlan_ieee_11i_encryption_modes 0
	get_wlan_ieee_11i_authentication_mode 0
	get_wlan_radio_enabled 0
	get_wlan_device_operation_mode 0
	get_wlan_authentication_service_mode 0
	get_wlan_total_associations 0
	get_wlan_associated_device 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable)
	get_wlan_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Status)
	get_wlan_status 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BSSID)
	get_wlan_bssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel)
	get_wlan_channel 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID)
	get_wlan_ssid 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled)
	get_wlan_mac_control_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex)
	get_wlan_wep_key_index 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes)
	get_wlan_basic_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode)
	get_wlan_basic_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes)
	get_wlan_wpa_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode)
	get_wlan_wpa_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes)
	get_wlan_ieee_11i_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode)
	get_wlan_ieee_11i_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled)
	get_wlan_radio_enabled 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode)
	get_wlan_device_operation_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode)
	get_wlan_authentication_service_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.TotalAssociations)
	get_wlan_total_associations 0
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}

set_lan_device() {
case "$1" in
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable)
	set_wlan_enable 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Status)
	return $FAULT_CPE_NON_WRITABLE_PARAMETER
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BSSID)
	return $FAULT_CPE_NON_WRITABLE_PARAMETER
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel)
	if [ $2 -lt 0 -o $2 -gt 255 ];then
		return $FAULT_CPE_INVALID_PARAMETER_VALUE
	fi
	set_wlan_channel 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID)
	set_wlan_ssid 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled)
	set_wlan_mac_control_enable 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex)
	set_wlan_wep_key_index 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes)
	set_wlan_basic_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode)
	set_wlan_basic_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes)
	set_wlan_wpa_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode)
	set_wlan_wpa_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes)
	set_wlan_ieee_11i_encryption_modes 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode)
	set_wlan_ieee_11i_authentication_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled)
	set_wlan_radio_enabled 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode)
	set_wlan_device_operation_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode)
	set_wlan_authentication_service_mode 0
	return $FAULT_CPE_NO_FAULT
	;;
	*)
	set_ip_interface_ip_address $1 $2
	result1=$?
	set_ip_interface_netmask $1 $2
	result2=$?
	if [ \( "$result1" != "$FAULT_CPE_NO_FAULT" \) -a \( "$result2" != "$FAULT_CPE_NO_FAULT" \) ]; then
		return $FAULT_CPE_INVALID_PARAMETER_NAME
	fi
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}

set_lan_device_notification() {
case "$1" in
	InternetGatewayDevice.)
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode" "0"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.)
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.channel" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode" "0"
	freecwmp_set_parameter_notification "$1" "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.)
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode" "0"
	freecwmp_set_parameter_notification "$1" "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.)
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1." "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode" "0"
	freecwmp_set_parameter_notification "$1" "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.)
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode" "0"
	freecwmp_set_parameter_notification "InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode" "0"
	freecwmp_set_parameter_notification "$1" "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Enable)
	set_wlan_enable 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Status)
	return $FAULT_CPE_NOTIFICATION_REJECTED
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BSSID)
	return $FAULT_CPE_NOTIFICATION_REJECTED
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Channel)
	set_wlan_channel 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID)
	set_wlan_ssid 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.MACAddressControlEnabled)
	set_wlan_mac_control_enable 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WEPKeyIndex)
	set_wlan_wep_key_index 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicEncryptionModes)
	set_wlan_basic_encryption_modes 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.BasicAuthenticationMode)
	set_wlan_basic_authentication_mode 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes)
	set_wlan_wpa_encryption_modes 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode)
	set_wlan_wpa_authentication_mode 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes)
	set_wlan_ieee_11i_encryption_modes 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode)
	set_wlan_ieee_11i_authentication_mode 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.RadioEnabled)
	set_wlan_radio_enabled 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceOperationMode)
	set_wlan_device_operation_mode 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AuthenticationServiceMode)
	set_wlan_authentication_service_mode 0 "$2"
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}
