#!/bin/sh
# Copyright (C) 2012 Luka Perkov <freecwmp@lukaperkov.net>

get_misc_cpu_usage() {
local val=`uptime | awk -F'average: ' '{ print $2 }' | awk -F',' '{ print $1 }' | awk -F'.' '{ print $2 }'`
ubus_freecwmp_output "Device.DeviceInfo.ProcessStatus.CPUUsage" "$val"
}

get_misc_process_number() {
local val=`ps | grep -v COMMAND | wc -l`
local type="xsd:unsignedInt"
ubus_freecwmp_output "Device.DeviceInfo.ProcessStatus.ProcessNumberOfEntries" "$val" "$type"
}

get_misc() {
case "$1" in
	Device.DeviceInfo.ProcessStatus.CPUUsage)
	get_misc_cpu_usage
	return $FAULT_CPE_NO_FAULT
	;;
	Device.DeviceInfo.ProcessStatus.ProcessNumberOfEntries)
	get_misc_process_number
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME
}
