#!/bin/sh
# Copyright (C) 2012 Luka Perkov <freecwmp@lukaperkov.net>

# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerPort
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerTransport
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerPort
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerTransport
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentDomain
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentTransport
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxy
# OPTIONAL: InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxyPort

get_line_enable() {
local num="$1"
local val=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip$num.enabled 2> /dev/null`
	let num=$num+1
	if [ "$val" = "0" ]; then
	    val="Disabled"
	else
	    val="Enabled"
	fi
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.Enable" "$val" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.Enable" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.Enable"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.Enable" "$val"
	;; 
esac  

}

set_line_enable() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.Enable"
case $action in
	set_value)
	if [ "$val" = "Enabled" ]; then
	    val="1"
	else
	    val="0"
	fi
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip$num.enabled="$val"
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}
get_line_sip_username() {
local num="$1"
local val=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip$num.defaultuser 2> /dev/null`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthUserName" "$val" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthUserName" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthUserName"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthUserName" "$val"
	;; 
esac  

}

set_line_sip_username() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthUserName"
case $action in
	set_value)
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip$num.defaultuser="$val"
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_line_sip_password() {
local num="$1"
local val=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip$num.secret 2> /dev/null`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthPassword" "$val" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthPassword" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthPassword"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthPassword" "$val"
	;; 
esac  

}

set_line_sip_password() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.AuthPassword"
case $action in
	set_value)
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip$num.secret="$val"
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_line_sip_uri() {
local num="$1"
local val=""
local domain=""
local username=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	domain=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip$num.domain 2> /dev/null`
	username=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip$num.defaultuser 2> /dev/null`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.URI" "$username@$domain" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.URI" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.URI"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.URI" "$val"
	;; 
esac  

}

set_line_sip_uri() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.$num.SIP.URI"
case $action in
	set_value)
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	local domain=${val#*@}
	if [ "$domain"]; then
	  /sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip$num.domain="$domain"
	fi
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_line_sip_proxyserver() {
local num="$1"
local val=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.SIP.sip_proxy 2> /dev/null`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "$val" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer"
	;; 
esac  

}

set_line_sip_proxyserver() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer"
case $action in
	set_value)
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.SIP.sip_proxy="$val"
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_line_sip_registrarserver() {
local num="$1"
local val=""
local type="xsd:string"
local permissions=""
case "$action" in
	get_value)
	val=`/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get voice_client.sip0.host 2> /dev/null`
	let num=$num+1
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer" "$val" "$permissions"
	;;
	get_name)
	let num=$num+1
	permissions="1"  
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer" "$val" "$permissions" "$type"
	;;
	get_notification)
	let num=$num+1
	freecwmp_get_parameter_notification "val" "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"
	;; 
esac  

}

set_line_sip_registrarserver() {
local num="$1"
local val="$2"
local parm="InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"
case $action in
	set_value)
	delay_service_restart "voice_client" "5"
	delay_service_restart "asterisk" "6"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip0.host="$val"
	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set voice_client.sip1.host="$val"
	;;
	set_notification)
	let num=$num+1
	freecwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_voice_service() {
case "$1" in
	InternetGatewayDevice.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver 0
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer)
	get_line_sip_proxyserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer)
	get_line_sip_registrarserver 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentDomain)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxy)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxyPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.)
	get_line_enable 0
	get_line_sip_username 0
	get_line_sip_password 0
	get_line_sip_uri 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable)
	get_line_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName)
	get_line_sip_username 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword)
	get_line_sip_password 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI)
	get_line_sip_uri 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.)
	get_line_sip_username 1
	get_line_sip_password 1
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable)
	get_line_enable 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName)
	get_line_sip_username 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword)
	get_line_sip_password 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI)
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME;
}

get_voice_service_notification() {
case "$1" in
	InternetGatewayDevice.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer)
	get_line_sip_proxyserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerTransport)
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer)
	get_line_sip_registrarserver
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerPort)
	return $FAULT_CPE_NO_FAULT  
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerTransport)
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentDomain)
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentTransport)
	return $FAULT_CPE_NO_FAULT   
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxy)
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxyPort)
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.)
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT  
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.)
	get_line_enable 0
	get_line_sip_username 0
	get_line_sip_password 0
	get_line_sip_uri 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable)
	get_line_enable 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName)
	get_line_sip_username 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword)
	get_line_sip_password 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI)
	get_line_sip_uri 0
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.)
	get_line_sip_username 1
	get_line_sip_password 1
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable)
	get_line_enable 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName)
	get_line_sip_username 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword)
	get_line_sip_password 1
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI)
	get_line_sip_uri 1
	return $FAULT_CPE_NO_FAULT
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME;
}


get_voice_service_name() {
case "$1" in
	
	InternetGatewayDevice.)
	freecwmp_output "InternetGatewayDevice.Services." "" "1"
	if [ "$2" = "0" ]; then
	freecwmp_output "InternetGatewayDevice.Services.VoiceService."  "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1."  "" "1"
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1."  "" "1"
	if [ "$2" = "0" ]; then
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1." "" "1"
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.)
	
	freecwmp_output "InternetGatewayDevice.Services.VoiceService." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1." "" "1"
	if [ "$2" = "0" ]; then
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1." "" "1"
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	
	;;
	InternetGatewayDevice.Services.VoiceService.1.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile." "" "1"
	if [ "$2" = "0" ]; then
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1." "" "1"	
 
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile."  "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1." "" "1" 
	
	
	  if [ "$2" = "0" ]; then
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1."  "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2."  "" "1"
	   
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line." "" "1"
	 if [ "$2" = "0" ]; then
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1."  "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1." "" "1"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2."  "" "1"
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	fi
	return $FAULT_CPE_NO_FAULT
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.)
	
	 freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP." "" "0"
	get_line_sip_proxyserver
	get_line_sip_registrarserver
	if [ "$2" = "1" ]; then
	
	return $FAULT_CPE_NO_FAULT
	fi
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_sip_proxyserver
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer)
	  if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_sip_registrarserver
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentDomain)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxy)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxyPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1." "" "1"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2." "" "1"
	      
	get_line_enable 0
	get_line_enable 1
	get_line_sip_username 0
	get_line_sip_username 1
	get_line_sip_password 0
	get_line_sip_password 1
	get_line_sip_uri 0
	get_line_sip_uri 1
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1." "" "0"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP." "" "0"
	get_line_enable 0
	get_line_sip_username 0
	get_line_sip_password 0
	get_line_sip_uri 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_enable 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP." "" "0"
	get_line_sip_username 0
	get_line_sip_password 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_sip_username 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_sip_password 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI)
	if [ "$2" = "1" ]; then
		return $FAULT_CPE_INVALID_ARGUMENTS
	fi
	get_line_sip_uri 0
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2." "" "0"
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP." "" "0"
	get_line_sip_username 1
	get_line_sip_password 1
	get_line_sip_uri 1
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.)
	freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP." "" "0"
	get_line_sip_username 1
	get_line_sip_password 1
        ;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable)
	get_line_enable 1
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName)
	get_line_sip_username 1
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword)
	get_line_sip_password 1
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI)
	get_line_sip_uri 1
	;;
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME;
}

set_voice_service() {
case "$1" in
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer)
	set_line_sip_proxyserver 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer)
	set_line_sip_registrarserver 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServerTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentDomain)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.UserAgentTransport)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxy)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.OutbandProxyPort)
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable)
	set_line_enable 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName)
	set_line_sip_username 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword)
	set_line_sip_password 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI)
	set_line_sip_uri 0 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable)
	set_line_enable 1 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName)
	set_line_sip_username 1 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword)
	set_line_sip_password 1 "$2"
	;;
	InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI)
	set_line_sip_uri 1 "$2"
	;;
esac
/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} commit
return $FAULT_CPE_INVALID_PARAMETER_NAME;
}

set_voice_service_notification()
{
case "$1" in
	InternetGatewayDevice.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer" "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer"  "0"
	  freecwmp_set_parameter_notification "$1" "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.ProxyServer)
	  set_line_sip_proxyserver 0 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.SIP.RegistrarServer)
	  set_line_sip_registrarserver 0 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;; 
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword"  "0"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.URI)
	  set_line_sip_uri 0 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthUserName)
	  set_line_sip_username 0 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.1.SIP.AuthPassword)
	  set_line_sip_password 0 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.)
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName"  "0"
	  freecwmp_output "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword"  "0"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.URI)
	  set_line_sip_uri 1 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthUserName)
	  set_line_sip_username 1 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;;
	  InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Line.2.SIP.AuthPassword)
	  set_line_sip_password 1 "$2"
	  return $FAULT_CPE_NO_FAULT
	  ;; 
esac
return $FAULT_CPE_INVALID_PARAMETER_NAME;
}
