#!/bin/sh
# Copyright (C) 2011-2012 Luka Perkov <freecwmp@lukaperkov.net>
# Copyright (C) 2013 Inteno Broadband Technology AB
#  Author Ahmed Zribi <ahmed.zribi@pivasoftware.com>
#  Author Mohamed Kallel <mohamed.kallel@pivasoftware.com>

get_device_info_hardware_version() {
	local val=""
	local dslAnnex=""
	dslAnnex=`cat /proc/nvram/dslAnnex 2> /dev/null`                                                
	val=`cat /etc/iop_version | cut -d'-' -f1 | sed s/$/"$dslAnnex"/ 2> /dev/null`
	echo "$val"
}

get_cache_InternetGatewayDevice_DeviceInfo() {
	get_object_cache_generic "InternetGatewayDevice.DeviceInfo." "0" "0"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.Manufacturer" "0" "$UCI_GET cwmp.cpe.manufacturer" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.ManufacturerOUI" "0" "cat /proc/nvram/BaseMacAddr | awk '{ print \$1\$2\$3}'" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.ProductClass" "0" "cat /etc/iop_version | cut -d'_' -f1" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.SerialNumber" "0" "cat /proc/nvram/SerialNumber" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.HardwareVersion" "0" "get_device_info_hardware_version" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.SoftwareVersion" "0" "cat /etc/iop_version | cut -d'_' -f2" "" "" "" "0" "1" "2"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.UpTime" "0" "" "" "cat /proc/uptime | cut -f1 -d'.'" "xsd:unsignedInt"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.DeviceLog" "0" "" "" "dmesg | tail -n5"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.SpecVersion" "0" "freecwmp_get_parameter_value \$param" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.DeviceInfo.ProvisioningCode" "1" "freecwmp_get_parameter_value \$param" "freecwmp_set_parameter_value \$param \$val" "" "" "0" "1" "2"
}

get_dynamic_InternetGatewayDevice_DeviceInfo() {
	return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_DeviceInfo() { 
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_DeviceInfo() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}