#!/bin/sh
# Copyright (C) 2013 Inteno Broadband Technology AB
#  Author Mohamed Kallel <mohamed.kallel@pivasoftware.com>

#InternetGatewayDevice.

append_restart_service_maps "$1" "InternetGatewayDevice.:cwmpd" || return
prefix_list="InternetGatewayDevice. $prefix_list"

get_cache_InternetGatewayDevice() {
	get_object_cache_generic "InternetGatewayDevice." "0" "0"
}

get_dynamic_InternetGatewayDevice() {
	return $FAULT_CPE_NO_FAULT
}

get_dynamic_linker_InternetGatewayDevice() {
	return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice() { 
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

#Device.
#To be added