#!/bin/sh
# Copyright (C) 2013 Inteno Broadband Technology AB
#   Author Feten Besbes <feten.besbes@pivasoftware.com>

get_firewall_rules() {
	local i=0
	local rule
	rule=`$UCI_SHOW firewall |grep "firewall\.@rule\[[0-9]\+\]=" | wc -l`
	if [ "$rule" != "" ]; then seq 1 $rule; fi
}

get_x_inteno_cfgobj_address_netmask() {
	local index=$1
	ip=`$UCI_GET firewall.@rule[$index].src_ip`
	ip=${ip// /,}
	if [ "$ip" = "" ]; then ip="0.0.0.0/0"; fi
	echo $ip
}

set_x_inteno_cfgobj_address_netmask() {
	local index=$1
	local val=$2
	val=${val//,/ }
	$UCI_SET firewall.@rule[$index].src_ip=""
	local src_ip
	for src_ip in $val; do
		$UCI_ADD_LIST firewall.@rule[$index].src_ip="$src_ip"
	done
	delay_service restart "firewall" "0"
}

get_x_bcm_com_ip_acc_list_cfgobj_acc_port() {
	local index=$1
	port=`$UCI_GET firewall.@rule[$index].dest_port`
	echo $port
}


set_x_bcm_com_ip_acc_list_cfgobj_acc_port() {
	local index=$1
	local val=$2
	$UCI_SET firewall.@rule[$index].dest_port=$val
	delay_service restart "firewall" "0"
}

get_x_bcm_com_ip_acc_list_cfgobj_enable() {
	local index=$1
	local enable=`$UCI_GET firewall.@rule[$index].enabled`
	echo ${enable:-1}
}

set_x_bcm_com_ip_acc_list_cfgobj_enable() {
	local index=$1
	local val=$2
	val=`echo $val|tr '[A-Z]' '[a-z]'`
	if [ "$val" = "true" -o "$val" = "1" ]; then
		val=""
	elif [ "$val" = "false" -o "$val" = "0" ]; then
		val="0"
	else
		return
	fi
	
	$UCI_SET firewall.@rule[$index].enabled=$val
	delay_service restart "firewall" "0"
}

get_cache_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	local val
	local instance index intf
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg." "0"
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj." "0"
	for instance in `get_firewall_rules`; do
		index=$(($instance-1))
		get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance." "0"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.Enable" "1" "get_x_bcm_com_ip_acc_list_cfgobj_enable $index" "set_x_bcm_com_ip_acc_list_cfgobj_enable $index \$val" "" "xsd:boolean"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.AccAddressAndNetMask" "1" "get_x_inteno_cfgobj_address_netmask $index" "set_x_inteno_cfgobj_address_netmask $index \$val"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.AccPort" "1" "get_x_bcm_com_ip_acc_list_cfgobj_acc_port $index" "set_x_bcm_com_ip_acc_list_cfgobj_acc_port $index \$val"
	done
}

get_dynamic_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_NO_FAULT
}

get_dynamic_linker_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}
