#!/bin/sh
# Copyright (C) 2013 Inteno Broadband Technology AB
#   Author Feten Besbes <feten.besbes@pivasoftware.com>

netmask2cidr ()
{
   local x=${1##*255.}
   set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) ${x%%.*}
   x=${1%%$3*}
   echo $(( $2 + (${#x}/4) ))
}

cidr2netmask ()
{
   set -- $(( 5 - ($1 / 8) )) 255 255 255 255 $(( (255 << (8 - ($1 % 8))) & 255 )) 0 0 0
   [ $1 -gt 1 ] && shift $1 || shift
   echo ${1-0}.${2-0}.${3-0}.${4-0}
}

get_firewall_rules() {
	local i=0
	local rule
	rule=`$UCI_SHOW firewall |grep "firewall\.@rule\[[0-9]\+\]=" | wc -l`
	if [ "$rule" != "" ]; then seq 1 $rule; fi
}

get_x_bcm_com_ip_acc_list_cfgobj_acc_address() {
	local index=$1
	ip=`$UCI_GET firewall.@rule[$index].src_ip | cut -f1 -d'/'`
	if [ "$ip" = "" ]; then ip="0.0.0.0"; fi
	echo $ip
}

get_x_bcm_com_ip_acc_list_cfgobj_acc_port() {
	local index=$1
	port=`$UCI_GET firewall.@rule[$index].dest_port`
	echo $port
}

get_x_bcm_com_ip_acc_list_cfgobj_acc_netmask() {
	local index=$1
	local src_ip=""
	local cidr=32
	local netmask
	src_ip=`$UCI_GET firewall.@rule[$index].src_ip`
	if [ "$src_ip" = "" ]; then echo 0.0.0.0; return; fi
	src_ip="$src_ip/"
	cidr=`echo $src_ip | cut -f2 -d'/'`
	if [ "$cidr" = "" ]; then
		netmask=255.255.255.255
	else
		netmask=`cidr2netmask $cidr`
	fi
	echo "$netmask"
}

set_x_bcm_com_ip_acc_list_cfgobj_acc_address() {
	local index=$1
	local val=$2
	local src_ip=`$UCI_GET firewall.@rule[$index].src_ip`
	if [ "$src_ip" = "" ]; then
		src_ip="$val/0"
	else
		local ip=${src_ip%%/*}
		src_ip=${src_ip/$ip/$val}
	fi
	$UCI_SET firewall.@rule[$index].src_ip="$src_ip"
	delay_service restart "firewall" "0"
}

set_x_bcm_com_ip_acc_list_cfgobj_acc_port() {
	local index=$1
	local val=$2
	$UCI_SET firewall.@rule[$index].dest_port=$val
	delay_service restart "firewall" "0"
}

set_x_bcm_com_ip_acc_list_cfgobj_acc_netmask() {
	local index=$1
	local val=$2
	val=`netmask2cidr $val`
	local src_ip=`$UCI_GET firewall.@rule[$index].src_ip`
	if [ "$src_ip" = "" ]; then
		src_ip="0.0.0.0/$val"
	else
		local ip=${src_ip%%/*}
		src_ip="$ip/$val"
	fi
	$UCI_SET firewall.@rule[$index].src_ip="$src_ip"
	delay_service restart "firewall" "0"
}

get_x_bcm_com_ip_acc_list_cfgobj_enable() {
	local index=$1
	local enable=`$UCI_GET firewall.@rule[$index].enabled`
	echo ${enable:-1}
}

set_x_bcm_com_ip_acc_list_cfgobj_enable() {
	local index=$1
	local val=$2
	val=`echo $val|tr '[A-Z]' '[a-z]'`
	if [ "$val" = "true" -o "$val" = "1" ]; then
		val=""
	elif [ "$val" = "false" -o "$val" = "0" ]; then
		val="0"
	else
		return
	fi
	
	$UCI_SET firewall.@rule[$index].enabled=$val
	delay_service restart "firewall" "0"
}

get_cache_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	local val
	local instance index intf
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg." "0"
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj." "0"
	for instance in `get_firewall_rules`; do
		index=$(($instance-1))
		get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance." "0"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.Enable" "1" "get_x_bcm_com_ip_acc_list_cfgobj_enable $index" "set_x_bcm_com_ip_acc_list_cfgobj_enable $index \$val" "" "xsd:boolean"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.AccAddress" "1" "get_x_bcm_com_ip_acc_list_cfgobj_acc_address $index" "set_x_bcm_com_ip_acc_list_cfgobj_acc_address $index \$val"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.AccPort" "1" "get_x_bcm_com_ip_acc_list_cfgobj_acc_port $index" "set_x_bcm_com_ip_acc_list_cfgobj_acc_port $index \$val"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_IpAccCfg.X_INTENO_SE_IpAccListCfgObj.$instance.AccNetMask" "1" "get_x_bcm_com_ip_acc_list_cfgobj_acc_netmask $index" "set_x_bcm_com_ip_acc_list_cfgobj_acc_netmask $index \$val"
	done
}

get_dynamic_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_NO_FAULT
}

get_dynamic_linker_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_X_INTENO_SE_IpAccCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}
