#!/bin/sh
# Copyright (C) 2015 Inteno Broadband Technology AB
#  Author Feten Besbes <feten.besbes@pivasoftware.com>

append_restart_service_maps "$1" "InternetGatewayDevice.X_INTENO_SE_Wifi.:network"  || return
local object="InternetGatewayDevice.X_INTENO_SE_Wifi."
prefix_list="$prefix_list $object"

get_wifi_frequency () {
	local wlctl="$1"
	local val=`wlctl -i $wlctl status |awk  '$1=="Chanspec:" {print$2}'`
	echo "$val"
}

get_wifi_maxassoc () {
	local wlctl="$1"
	local val=`$UCI_GET wireless.$wlctl.maxassoc` 
	echo $val
}

set_wifi_maxassoc () {
	local wlctl="$1"
	local val="$2"
	$UCI_SET wireless.$wlctl.maxassoc=$val
	delay_service reload "network" "1"
}

get_cache_InternetGatewayDevice_X_INTENO_SE_Wifi() {
	local val
	local idev
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_Wifi." "0"
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_Wifi.Radio" "0"
	for wlctl_num in `$UCI_SHOW wireless|grep "wireless\.wl[0-9]\+=wifi-device" | awk -F '[.=]' '{print $2}'`; do
		wnum=${wlctl_num#wl*}
		let "wnum = $wnum + 1"
		get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_Wifi.Radio.$wnum" "0"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_Wifi.Radio.$wnum.Frequency" "0" "get_wifi_frequency $wlctl_num"
		get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_Wifi.Radio.$wnum.MaxAssociations" "1" "get_wifi_maxassoc $wlctl_num" "set_wifi_maxassoc $wlctl_num \$val"
	done
}

get_dynamic_InternetGatewayDevice_X_INTENO_SE_Wifi() {
	return $FAULT_CPE_NO_FAULT
}

get_dynamic_linker_InternetGatewayDevice_X_INTENO_SE_Wifi() {
    return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_X_INTENO_SE_Wifi() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_X_INTENO_SE_Wifi() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}
