#!/bin/sh
# Copyright (C) 2015 Inteno Broadband Technology AB
#  Author Anis Ellouze <anis.ellouze@pivasoftware.com>
#  Author Simon Kers <simon.kers@inteno.se>

local service="/etc/init.d/power_mgmt"
local object="InternetGatewayDevice.X_INTENO_SE_PowerManagement."

# Add TR-069 object to cache if there is a service
if [ -e $service ]
then
	prefix_list="$prefix_list $object"
fi

get_power_mgmt_value() {
	local power_type="$1"
	local val=`$UCI_GET power_mgmt.power_mgmt.$power_type`
	echo ${val:-0}
}

set_power_mgmt_param_value() {
	local power_type="$1"
	local status="$2"
	if [ "$status" = "true" -o "$status" = "1" ]; then
		$UCI_SET power_mgmt.power_mgmt.$power_type="1"
	elif [ "$status" = "false" -o "$status" = "0" ]; then
		$UCI_SET power_mgmt.power_mgmt.$power_type="0"
	else
		return
	fi
	delay_service restart "power_mgmt" "1"
}

get_power_mgmt_nbr_interfaces() {
	local status="$1"
	local val=`pwrctl show |awk '$1=="Powered" && $2=="'$status':" {print $3}'`
	echo $val
}

get_cache_InternetGatewayDevice_X_INTENO_SE_PowerManagement() {
	local val
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_PowerManagement." "0"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_PowerManagement.EthernetAutoPowerDownEnable" "1" "get_power_mgmt_value ethapd" "set_power_mgmt_param_value ethapd \$val" "" "xsd:boolean" 
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_PowerManagement.EnergyEfficientEthernetEnable" "1" "get_power_mgmt_value eee" "set_power_mgmt_param_value eee \$val" "" "xsd:boolean"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_PowerManagement.NumberOfEthernetInterfacesPoweredUp" "0" "" "" "get_power_mgmt_nbr_interfaces up" "xsd:unsignedInt"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_PowerManagement.NumberOfEthernetInterfacesPoweredDown" "0" "" "" "get_power_mgmt_nbr_interfaces down" "xsd:unsignedInt"
}

get_dynamic_InternetGatewayDevice_X_INTENO_SE_PowerManagement() {
	return $FAULT_CPE_NO_FAULT
}

get_dynamic_linker_InternetGatewayDevice_X_INTENO_SE_PowerManagement() {
    return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_X_INTENO_SE_PowerManagement() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_X_INTENO_SE_PowerManagement() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}
