#!/bin/sh
# Copyright (C) 2011-2012 Luka Perkov <freecwmp@lukaperkov.net>
# Copyright (C) 2013 Inteno Broadband Technology AB
#  Author Feten Besbes <feten.besbes@pivasoftware.com>

set_x_bcm_password() {
	local usr_type=$1
	local new_pwd=$2
	passwd $usr_type <<EOF > /dev/null
$new_pwd
$new_pwd
EOF
}

get_cache_InternetGatewayDevice_X_INTENO_SE_LoginCfg() {
	get_object_cache_generic "InternetGatewayDevice.X_INTENO_SE_LoginCfg." "0"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_LoginCfg.AdminPassword" "1" "" "set_x_bcm_password admin \$val" "" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_LoginCfg.SupportPassword" "1" "" "set_x_bcm_password support \$val" "" "" "" "" "" "1"
	get_param_cache_generic "InternetGatewayDevice.X_INTENO_SE_LoginCfg.UserPassword" "1" "" "set_x_bcm_password user \$val" "" "" "" "" "" "1"
}

get_dynamic_InternetGatewayDevice_X_INTENO_SE_LoginCfg() {
	return $FAULT_CPE_NO_FAULT
}

add_object_InternetGatewayDevice_X_INTENO_SE_LoginCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}

delete_object_InternetGatewayDevice_X_INTENO_SE_LoginCfg() {
	return $FAULT_CPE_INVALID_PARAMETER_NAME
}
