#!/bin/sh

uci -q batch <<-EOT
        delete firewall.icwmp
        set firewall.icwmp=include
        set firewall.icwmp.path=/etc/firewall.icwmp
        set firewall.icwmp.reload=1
        commit firewall
EOT

exit 0

