#!/bin/sh

check_network=`uci get -q ucitrack.@network[0].affects|grep iccu` 
if [ "_$check_network" = "_" ];then
    uci add_list ucitrack.@network[0].affects=iccu
fi
check_cwmp=`uci get -q ucitrack.@cwmp[0]`
if [ "_$check_cwmp" = "_" ];then
    uci add ucitrack cwmp
    uci set ucitrack.@cwmp[0].init=cwmpd
    uci add_list ucitrack.@cwmp[0].affects=iccu
    uci add ucitrack iccu
    uci set ucitrack.@iccu[0].init=iccu
fi
uci commit

/etc/init.d/iccu enable
/etc/init.d/iccu boot

cat /etc/init.d/cwmpd|grep -v "/etc/cwmpd/scripts/iccu_enable && rm /etc/cwmpd/scripts/iccu_enable" > /etc/init.d/cwmpd.new
mv /etc/init.d/cwmpd.new /etc/init.d/cwmpd
chmod +x /etc/init.d/cwmpd